Repository WildCodeSchool-2023-09/php-p2-strashelp, pull requests merged in 2023-11, with the labels that each got.

#2 ok
  public/assets/css/style.css
  public/assets/css/styleNavBar.css
  public/assets/css/stylefooter.css
  public/assets/css/variables.css
  public/assets/images/logo-strashelp-300px.png
  src/Controller/AnnoncesController.php
  src/Controller/ConnexionController.php
  src/Controller/ContactController.php
  src/Controller/DepotController.php
  src/Controller/InscriptionController.php
  src/Controller/MentionLegalesController.php
  src/View/Components/_footer.html.twig
  src/View/Components/_navbar.html.twig
  src/View/annonces/_annonces.html.twig
  src/View/connexion/connexion.html.twig
  src/View/contact/contact.html.twig
  src/View/deposeruneannonce/deposeruneannonce.html.twig
  src/View/inscription/inscription.html.twig
  src/View/layout.html.twig
  src/View/mentionlegales/mentionlegales.html.twig
  src/routes.php
Labels: enhancement

#3 Réalisation login
  public/assets/css/_login.css
  src/Controller/UserController.php
  src/Model/UserManager.php
  src/View/Components/_login.html.twig
Labels: bug

#22 update dev architecture
  public/assets/css/style.css
  src/Controller/AnnonceController.php
  src/Controller/ConnexionController.php
  src/Controller/ContactController.php
  src/Controller/DepotController.php
  src/Controller/InscriptionController.php
  src/Controller/MentionLegalesController.php
  src/Controller/UserController.php
  src/Model/AnnonceManager.php
  src/View/Annonce/_annonces.html.twig
  src/View/Components/_form_register.html.twig
  src/View/Components/_login.html.twig
  src/View/Components/_navbar.html.twig
  src/View/connexion/connexion.html.twig
  src/View/contact/contact.html.twig
  src/View/deposeruneannonce/deposeruneannonce.html.twig
  src/View/inscription/inscription.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: URGENT

#5 Contactform
  phpmd.xml
  public/assets/css/uikit.css
  public/assets/images/planche-ambiance-projet-2-strashelp-0.3-opacity.jpg
  public/assets/images/planche-ambiance-projet-2-strashelp.jpg
  src/Controller/ContactController.php
  src/Model/ContactManager.php
  src/View/Components/_form_contact.html.twig
  src/View/Home/index.html.twig
  src/View/contact/contact.html.twig
Labels: help wanted

#27 Toggle switch 3 entrees
  public/assets/css/style.css
  public/assets/css/toggle-switch.css
  public/assets/css/trouver-proposer.css
  public/assets/images/illustration-proposer-1.png
  public/assets/images/illustration-proposer-2.png
  public/assets/images/illustration-proposer-3.png
  public/assets/images/illustration-trouver-1.png
  public/assets/images/illustration-trouver-2.png
  public/assets/images/illustration-trouver-3.png
  src/View/Components/_footer.html.twig
  src/View/Components/_navbar.html.twig
  src/View/Components/_toggle-switch.html.twig
  src/View/Components/_trouver-proposer.html.twig
  src/View/layout.html.twig
Labels: enhancement, URGENT

#26 Page d'accueil
  public/assets/css/accueil.css
  src/View/Accueil/accueil.html.twig
  src/View/Home/index.html.twig
Labels: enhancement, URGENT

#21 Searchbar2 - UPDATE 20/11/23
  public/assets/css/_searchbar.css
  public/assets/css/style.css
  public/assets/css/variables.css
  src/Controller/AbstractController.php
  src/Controller/AnnoncesController.php
  src/Controller/CategoryController.php
  src/Model/CategoryManager.php
  src/Model/ItemManager.php
  src/View/Components/_searchbar.html.twig
  src/View/Home/index.html.twig
  src/View/Searchbar/searchbar.html.twig
  src/View/annonces/_annonces.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: URGENT

#32 Fix
  database.sql
  public/assets/JS/dark-mode.js
  public/assets/JS/easter-egg.js
  public/assets/JS/script.js
  public/assets/JS/script_loadmore.js
  public/assets/css/_login.css
  public/assets/css/style.css
  public/assets/css/variables.css
  public/assets/images/655b5f56a298d8.57702228activités-de-babysitting-à-faire-avec-les-enfants-3514-1655991416.jpg
  src/Controller/AbstractController.php
  src/Controller/AnnonceController.php
  src/Controller/AnnoncesController.php
  src/Controller/CategoryController.php
  src/Controller/UserController.php
  src/Model/AnnonceManager.php
  src/Model/CategoryManager.php
  src/View/Annonce/annonces.html.twig
  src/View/Annonce/detail-annonce.html.twig
  src/View/Annonce/repondreannonce.html.twig
  src/View/Components/_card.html.twig
  src/View/Components/_footer.html.twig
  src/View/Components/_form_register.html.twig
  src/View/Components/_login.html.twig
  src/View/Components/_navbar.html.twig
  src/View/Components/_searchbar.html.twig
  src/View/Components/_toggle-switch.html.twig
  src/View/Home/index.html.twig
  src/View/annonces/_annonces.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: URGENT
